[package]
name = "supa-mdx-lint"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
log = "0.4.22"
markdown = "1.0.0-alpha.21"
serde_yaml = "0.9.34"
toml = "0.8.19"

[dev-dependencies]
ctor = "0.2.8"
env_logger = "0.11.5"
